/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package card.view;

import card.connect.CarDAO;
import card.connect.SmartCard;
import card.connect.UserDAO;
import card.model.Cache;
import card.model.History;
import card.model.User;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Car_Managenment extends javax.swing.JFrame {

    DefaultTableModel tablexevao;
    DefaultTableModel tablexera;
    ArrayList<History> listHistory;
    SmartCard smartCard;
    public User user;

    public Car_Managenment() {

        initComponents();

        tablexevao = (DefaultTableModel) tbl_vao.getModel();
        tablexera = (DefaultTableModel) tbl_ra.getModel();
        showHistoryRa();
        showHistoryVao();
        new Thread() {
            public void run() {
                while (true) {

                    Calendar calendar = new GregorianCalendar();
                    int hour = calendar.get(Calendar.HOUR);
                    int minute = calendar.get(Calendar.MINUTE);
                    int second = calendar.get(Calendar.SECOND);
                    int day = calendar.get(Calendar.DAY_OF_MONTH);
                    int month = calendar.get(Calendar.MONTH) + 1;
                    int year = calendar.get(Calendar.YEAR);

                    int PM_AM = calendar.get(Calendar.AM_PM);
                    String day_n;
                    if (PM_AM == 1) {
                        day_n = "PM";
                    } else {
                        day_n = "AM";
                    }
                    String date = day + "/" + month + "/" + year;
                    String time = hour + ":" + minute + ":" + second + " " + day_n;
                    lbDate.setText(date);
                    lbclock2.setText(time);

                }

            }
        }.start();
            this.setLocationRelativeTo(null);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_bsxevao = new javax.swing.JTextField();
        btn_chovao = new javax.swing.JButton();
        btn_quetthevao = new javax.swing.JButton();
        txt_lanvao_idcard = new javax.swing.JLabel();
        txt_lanvao_bsCard = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_lanvao_hoten = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_bsxera = new javax.swing.JTextField();
        btn_chora = new javax.swing.JButton();
        btn_quetthera = new javax.swing.JButton();
        txt_lanra_idcard = new javax.swing.JLabel();
        txt_lanra_bsCard = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_lanra_hoten = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbclock2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vao = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ra = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxvao = new javax.swing.JComboBox<>();
        jComboBoxra = new javax.swing.JComboBox<>();
        txt_search_lanra = new javax.swing.JTextField();
        bt_search_ra = new javax.swing.JButton();
        txt_search_lanvao = new javax.swing.JTextField();
        bt_search_vao = new javax.swing.JButton();
        btn_refresh_vao = new javax.swing.JButton();
        btn_refresh_ra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(895, 400));
        jTabbedPane1.setRequestFocusEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(895, 450));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("LÀN VÀO"));

        jLabel2.setText("Mã thẻ");

        jLabel3.setText("Biển Số");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Biển Số Xe Vào");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txt_bsxevao, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bsxevao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_chovao.setText("Cho Vào");
        btn_chovao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chovaoActionPerformed(evt);
            }
        });

        btn_quetthevao.setText("Quẹt Thẻ");
        btn_quetthevao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quetthevaoActionPerformed(evt);
            }
        });

        jLabel12.setText("Họ Tên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_quetthevao, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_chovao, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_lanvao_bsCard, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_lanvao_idcard, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_lanvao_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lanvao_idcard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lanvao_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lanvao_bsCard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_quetthevao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chovao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("LÀN RA"));

        jLabel5.setText("Mã thẻ");

        jLabel6.setText("Biển Số");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Biển Số Xe Ra");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txt_bsxera, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bsxera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_chora.setText("Cho Ra");
        btn_chora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choraActionPerformed(evt);
            }
        });

        btn_quetthera.setText("Quẹt Thẻ");
        btn_quetthera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quettheraActionPerformed(evt);
            }
        });

        jLabel13.setText("Họ Tên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btn_quetthera, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_chora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_lanra_bsCard, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txt_lanra_idcard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_lanra_hoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lanra_idcard, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lanra_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lanra_bsCard, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_quetthera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chora, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÍ BÃI ĐỖ XE");

        jLabel9.setText("Ngày:");

        lbDate.setText("jLabel11");

        jLabel11.setText("Giờ:");

        lbclock2.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(514, 514, 514)
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel10)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lbclock2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel1)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(lbDate)
                    .addComponent(jLabel11)
                    .addComponent(lbclock2))
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        jTabbedPane1.addTab("Trang Chủ", jPanel1);

        jPanel7.setPreferredSize(new java.awt.Dimension(888, 480));

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Lịch Sử Làn Vào"));

        tbl_vao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã thẻ", "Họ Tên", "Giá Tiền", "Biển Số", "Giờ Vào"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_vao);
        if (tbl_vao.getColumnModel().getColumnCount() > 0) {
            tbl_vao.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbl_vao.getColumnModel().getColumn(1).setPreferredWidth(70);
            tbl_vao.getColumnModel().getColumn(2).setResizable(false);
            tbl_vao.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbl_vao.getColumnModel().getColumn(3).setPreferredWidth(70);
            tbl_vao.getColumnModel().getColumn(4).setPreferredWidth(70);
            tbl_vao.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Lịch Sử Làn Ra"));

        tbl_ra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã thẻ", "Họ Tên", "Giá Tiền", "Biển Số", "Giờ Ra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_ra);
        if (tbl_ra.getColumnModel().getColumnCount() > 0) {
            tbl_ra.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbl_ra.getColumnModel().getColumn(1).setPreferredWidth(70);
            tbl_ra.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbl_ra.getColumnModel().getColumn(3).setPreferredWidth(70);
            tbl_ra.getColumnModel().getColumn(4).setPreferredWidth(70);
            tbl_ra.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("LỊCH SỬ VÀO RA");

        jComboBoxvao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Biển Số" }));

        jComboBoxra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Biển Số" }));
        jComboBoxra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxraActionPerformed(evt);
            }
        });

        txt_search_lanra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_lanraActionPerformed(evt);
            }
        });

        bt_search_ra.setText("Tìm kiếm");
        bt_search_ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_search_raActionPerformed(evt);
            }
        });

        txt_search_lanvao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_lanvaoActionPerformed(evt);
            }
        });

        bt_search_vao.setText("Tìm kiếm");
        bt_search_vao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_search_vaoActionPerformed(evt);
            }
        });

        btn_refresh_vao.setText("Làm mới");
        btn_refresh_vao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_vaoActionPerformed(evt);
            }
        });

        btn_refresh_ra.setText("Làm mới");
        btn_refresh_ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_raActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(402, 402, 402))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxvao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_search_lanvao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_search_vao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_refresh_vao)
                .addGap(19, 19, 19))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                                .addComponent(jComboBoxra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_search_lanra, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_search_ra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_refresh_ra)
                                .addGap(8, 8, 8)))
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxvao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search_lanvao)
                    .addComponent(bt_search_vao)
                    .addComponent(btn_refresh_vao))
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search_lanra)
                    .addComponent(bt_search_ra)
                    .addComponent(btn_refresh_ra))
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Lịch Sử Ra Vào", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chovaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chovaoActionPerformed
        long now = System.currentTimeMillis();
        Timestamp time = new Timestamp(now);
        String userId = txt_lanvao_idcard.getText();
        String bienSo = txt_bsxevao.getText();
        User user1 = UserDAO.getUser(user.getId());
        System.out.println(user1.getMoney());
        long price = 20000;
        int type = 1;
        if (user1 == null) {
            JOptionPane.showMessageDialog(this, "Thẻ Không Có Trong Hệ Thống");
        } else {
            if (user1.getStatus() != 0) {
                JOptionPane.showMessageDialog(this, "Thẻ Đã Được Sử Dụng Cho Xe Khác");
            } else {
                if (!checkBienSo(bienSo, user1.getBienSo())) {
                    JOptionPane.showMessageDialog(this, "Biển Số Xe Không Đúng");
                } else {
                    if (checkMoney(user1)) {
                        JOptionPane.showMessageDialog(this, "Thông Tin Hợp Lệ");
                        History his = new History(bienSo, time, price, type, userId);
                        
                        try {
                            String newMoney = String.valueOf(user1.getMoney() - 20000);
                            smartCard.topUpcard(newMoney);
                            CarDAO.insertHistory(his);
                            UserDAO.updateStatus(userId, 1);
                            UserDAO.deductMoney(user1, 20000);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                        showHistoryVao();
                    } else {
                        JOptionPane.showMessageDialog(this, "Trong Thẻ Không Đủ Tiền");
                    }
                    {

                    }
                }
            }
        }
        reset();

    }//GEN-LAST:event_btn_chovaoActionPerformed

    private void btn_choraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choraActionPerformed
        String userId = txt_lanra_idcard.getText();
        User user = UserDAO.getUser(userId);
        String bienSo = txt_bsxera.getText();
        long now = System.currentTimeMillis();
        Timestamp time = new Timestamp(now);
        long price = 20000;
        int type = 2;
        if (user == null) {
            JOptionPane.showMessageDialog(this, "Thẻ Không Có Trong Hệ Thống");
        } else {
            if (user.getStatus() != 1) {
                JOptionPane.showMessageDialog(this, "Xe Không Có Trong Bãi Đỗ");
            } else {
                if (!checkBienSo(bienSo, user.getBienSo())) {
                    JOptionPane.showMessageDialog(this, "Biển Số Xe Không Đúng");
                } else {
                    History his = new History(bienSo, time, price, type, userId);
                    CarDAO.insertHistory(his);
                    UserDAO.updateStatus(userId, 0);
                    showHistoryRa();
                }
            }
        }
        reset();
    }//GEN-LAST:event_btn_choraActionPerformed

    private void btn_quetthevaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quetthevaoActionPerformed

        try {
            smartCard = new SmartCard();
            boolean connect = smartCard.connectCard();
            if (connect) {
                user = smartCard.readAllData();
            }
            byte[] publicKey = UserDAO.gePublicKey(user.getId());
            boolean auth = smartCard.authenticate(publicKey);
            if(!auth)
            {
                JOptionPane.showMessageDialog(this, "Không phải thẻ phát hành", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {

        }
        txt_lanvao_hoten.setText(user.getFullName());
        txt_lanvao_bsCard.setText(user.getBienSo());
        txt_lanvao_idcard.setText(user.getId());

    }//GEN-LAST:event_btn_quetthevaoActionPerformed

    private void btn_quettheraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quettheraActionPerformed
        try {
            smartCard = new SmartCard();
            boolean connect = smartCard.connectCard();
            if (connect) {
                user = smartCard.readAllData();
            }
        } catch (Exception e) {

        }
        txt_lanra_idcard.setText(user.getId());
        txt_lanra_bsCard.setText(user.getBienSo());
        txt_lanra_hoten.setText(user.getFullName());
    }//GEN-LAST:event_btn_quettheraActionPerformed

    private void txt_search_lanvaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_lanvaoActionPerformed
       
    }//GEN-LAST:event_txt_search_lanvaoActionPerformed

    private void btn_refresh_raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_raActionPerformed
        showHistoryRa();
        showHistoryVao();
        txt_search_lanra.setText("");
        jComboBoxra.setSelectedIndex(0);
    }//GEN-LAST:event_btn_refresh_raActionPerformed

    private void txt_search_lanraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_lanraActionPerformed
      
    }//GEN-LAST:event_txt_search_lanraActionPerformed

    private void btn_refresh_vaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_vaoActionPerformed
        showHistoryRa();
        showHistoryVao();
        txt_search_lanvao.setText("");
        jComboBoxvao.setSelectedIndex(0);
    }//GEN-LAST:event_btn_refresh_vaoActionPerformed

    private void jComboBoxraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxraActionPerformed
        showHistoryRa();
        showHistoryVao();
    }//GEN-LAST:event_jComboBoxraActionPerformed

    private void bt_search_vaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_search_vaoActionPerformed
        int selectedItem = jComboBoxvao.getSelectedIndex();
        String txt = txt_search_lanvao.getText();
        if(selectedItem == 0){
            listHistory = CarDAO.searchHistoryByUserId(txt,1);
            tablexevao.setRowCount(0);
            listHistory.forEach((his) -> {
            User user = UserDAO.getUser(his.getUserId());
            tablexevao.addRow(new Object[]{
                tablexevao.getRowCount() + 1, his.getUserId(), user.getFullName(),his.getMoney(), his.getBienso(), his.getTime()
            });
        });
        }else{
            listHistory = CarDAO.searchHistoryByCarNumber(txt,1);
            tablexevao.setRowCount(0);
            listHistory.forEach((his) -> {
            User user = UserDAO.getUser(his.getUserId());
            tablexevao.addRow(new Object[]{
                tablexevao.getRowCount() + 1, his.getUserId(), user.getFullName(),his.getMoney(), his.getBienso(), his.getTime()
            });
        });
        }
    }//GEN-LAST:event_bt_search_vaoActionPerformed

    private void bt_search_raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_search_raActionPerformed
          int selectedItem = jComboBoxra.getSelectedIndex();
        String txt = txt_search_lanra.getText();
        if(selectedItem == 0){
            listHistory = CarDAO.searchHistoryByUserId(txt,2);
            tablexera.setRowCount(0);
            listHistory.forEach((his) -> {
            User user = UserDAO.getUser(his.getUserId());
            tablexera.addRow(new Object[]{
                tablexera.getRowCount() + 1, his.getUserId(), user.getFullName(),his.getMoney(), his.getBienso(), his.getTime()
            });
        });
        }else{
            listHistory = CarDAO.searchHistoryByCarNumber(txt,2);
            tablexera.setRowCount(0);
            listHistory.forEach((his) -> {
            User user = UserDAO.getUser(his.getUserId());
            tablexera.addRow(new Object[]{
                tablexera.getRowCount() + 1, his.getUserId(), user.getFullName(),his.getMoney(), his.getBienso(), his.getTime()
            });
        });
        }
    }//GEN-LAST:event_bt_search_raActionPerformed

    /**
     * @param args the command line arguments
     */
    public static boolean checkBienSo(String bienSo, String bienSoVao) {
        if (bienSo.equals(bienSoVao)) {
            return true;
        }
        return false;
    }



    public static boolean checkMoney(User user) {
        if (user.getMoney() < 20000) {
            return false;
        }
        return true;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Car_Managenment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Car_Managenment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Car_Managenment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Car_Managenment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Car_Managenment().setVisible(true);
            }
        });
    }

    public void showHistoryVao() {
        listHistory = CarDAO.getAllByType(1);
//        System.out.println(listHistory.get(1));
        tablexevao.setRowCount(0);
        listHistory.forEach((his) -> {
            User user = UserDAO.getUser(his.getUserId());
            tablexevao.addRow(new Object[]{
                tablexevao.getRowCount() + 1, his.getUserId(), user.getFullName(),his.getMoney(), his.getBienso(), his.getTime()
            });
        });
    }

    public void showHistoryRa() {
        listHistory = CarDAO.getAllByType(2);

        tablexera.setRowCount(0);
        listHistory.forEach((his) -> {
            User user = UserDAO.getUser(his.getUserId());
            tablexera.addRow(new Object[]{
                tablexera.getRowCount() + 1, his.getUserId(), user.getFullName(),his.getMoney(),his.getBienso(), his.getTime()
            });
        });
    }

    public void reset() {
        txt_bsxera.setText("");
        txt_bsxevao.setText("");
        txt_lanra_bsCard.setText("");
        txt_lanvao_bsCard.setText("");
        txt_lanra_idcard.setText("");
        txt_lanvao_idcard.setText("");
        txt_lanra_hoten.setText("");
        txt_lanvao_hoten.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_search_ra;
    private javax.swing.JButton bt_search_vao;
    private javax.swing.JButton btn_chora;
    private javax.swing.JButton btn_chovao;
    private javax.swing.JButton btn_quetthera;
    private javax.swing.JButton btn_quetthevao;
    private javax.swing.JButton btn_refresh_ra;
    private javax.swing.JButton btn_refresh_vao;
    private javax.swing.JComboBox<String> jComboBoxra;
    private javax.swing.JComboBox<String> jComboBoxvao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbclock2;
    private javax.swing.JTable tbl_ra;
    private javax.swing.JTable tbl_vao;
    private javax.swing.JTextField txt_bsxera;
    private javax.swing.JTextField txt_bsxevao;
    private javax.swing.JLabel txt_lanra_bsCard;
    private javax.swing.JLabel txt_lanra_hoten;
    private javax.swing.JLabel txt_lanra_idcard;
    private javax.swing.JLabel txt_lanvao_bsCard;
    private javax.swing.JLabel txt_lanvao_hoten;
    private javax.swing.JLabel txt_lanvao_idcard;
    private javax.swing.JTextField txt_search_lanra;
    private javax.swing.JTextField txt_search_lanvao;
    // End of variables declaration//GEN-END:variables
}
